name: Hygiene Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm build
        env:
          AZURE_OPEN_AI_URL: '${{secrets.AZURE_OPEN_AI_URL}}'
          AZURE_OPEN_AI_KEY: '${{secrets.AZURE_OPEN_AI_KEY}}'
          KINDE_CLIENT_ID: '${{secrets.KINDE_CLIENT_ID}}'
          KINDE_CLIENT_SECRET: '${{secrets.KINDE_CLIENT_SECRET}}'
          KINDE_ISSUER_URL: '${{secrets.KINDE_ISSUER_URL}}'
          KINDE_SITE_URL: '${{secrets.KINDE_SITE_URL}}'
          KINDE_POST_LOGOUT_REDIRECT_URL: '${{secrets.KINDE_POST_LOGOUT_REDIRECT_URL}}'
          KINDE_POST_LOGIN_REDIRECT_URL: '${{secrets.KINDE_POST_LOGIN_REDIRECT_URL}}'

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm lint

  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v3
  #       with:
  #         version: 9
  #     - name: Use Node.JS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'pnpm'
  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile
  #     - name: Run test
  #       run: pnpm test
